### Obtener registros
GET http://localhost:3000/

### Crear un nuevo registro JSON
POST http://localhost:3000/
Content-Type: application/json

{
  "nombre": "Richard Peña",
  "email": "richard.penab@gmail.com",
  "telefono": "+56944175484",
  "empresa": "Mente Ingeniería"
}

### Actualizar un valor
PATCH http://localhost:3000/
Content-Type: application/json

{
  "id": 169,
  "nombre": "Soy virgen",
  "email": "virgen@virginidad.com"
}

