CREATE TABLE tblContactos (
    id INT(11) AUTO_INCREMENT NOT NULL,
    nombre VARCHAR(50) NOT NULL,
    email VARCHAR(50) NOT NULL,
    telefono VARCHAR(50) NULL,
    empresa VARCHAR(50) NULL,
    medio VARCHAR(30) NULL,
    fechaHora TIMESTAMP DEFAULT CURRENT_TIMESTAMP NULL,
    PRIMARY KEY (id)
);
